### ISSUE TITLE
Reference surface normals for `modepy.Face`s

### ISSUE THREAD

**Issue by thomasgibson** [inducer/modepy#35]
In preparation for doing entropy-stable DG, we will need to access the surface normals defined on the reference element.

My idea is to augment the [Face class](https://github.com/inducer/modepy/blob/8a532888b70ed738c32cf633e87cb8e5b83c9c3e/modepy/shapes.py#L250) with an additional attribute: `surface_normal`.

Using this issue to track discussion/question relating to this. Will likely involve https://github.com/inducer/pymbolic to generate functions which can act on arbitrary faces, defined uniquely by their vertices, to generate the appropriate normal for each face.

**Comment by alexfikl** [comment]
[inducer/pymbolic](https://github.com/inducer/pymbolic) doesn't have much geometry stuff in it (yet), so it might be some work to get normals generically that way.

Currently the faces vertices are pretty much hardcoded (like [here](https://github.com/inducer/modepy/blob/8a532888b70ed738c32cf633e87cb8e5b83c9c3e/modepy/shapes.py#L328-L344)). Would it be horrible to just hardcode the normals too?

**Comment by thomasgibson** [comment]
Not at all, I think. It's not the nice general solution we talked about the other day, but I don't have any reservations about doing just that!

**Comment by alexfikl** [comment]
> Not at all, I think. It's not the nice general solution we talked about the other day, but I don't have any reservations about doing just that!

If you had some general solution in mind, then yes, definitely cleaner! Having thought about it a bit more, it's probably not that hard to throw some geometric algebra at it and get the normals.

**Comment by inducer** [comment]
Hmm... I didn't like where the discussion was going, so... challenge accepted. #36. :)
