### ISSUE TITLE
`submesh_for_shape` should support generic tensor products

### ISSUE THREAD

**Issue by inducer** [inducer/modepy#49]
(This'll be needed/become possible after #41 merges.)

cc @alexfikl

**Comment by alexfikl** [comment]
Does this require any special support? I was hoping it would just work™ based on the node tuples it gets (should test that!).

**Comment by inducer** [comment]
I assumed it didn't since `submesh_for_shape` was specialized for `Hypercube`. Maybe just broadening it to `TensorProductShape` suffices?

**Comment by inducer** [comment]
Closing here, adding to my review.

**Comment by alexfikl** [comment]
Actually, just looked over it a bit and it should fail for `line x triangle` because of 
```
    vertex_node_tuples = [nt[::-1] for nt in gnitb(2, dims)]
```
which assumes hypercubes. Should be possible to fix that by taking the `vertex_node_tuples` to be the 0-order node tuples for that shape.
