### ISSUE TITLE
Missing tag/pypi package for v2021.2.1?

### ISSUE THREAD

**Issue by matthiasdiener** [inducer/modepy#64]
https://github.com/inducer/modepy/blob/main/modepy/version.py shows version 2021.2.1, but the latest tag and pypi package are at v2021.1.

**Comment by inducer** [comment]
That was a preemptive bump to an unreleased version in https://github.com/inducer/modepy/commit/2e7cb99e3f21a704bda22f3e1819cd53cc69a1cc
